services:
#  database:
#    container_name: h2
#    image: oscarfonts/h2:latest
#    ports:
#      - 1521:1521
#      - 8082:81
#    environment:
#      H2_OPTIONS: -ifNotExists -web -webAllowOthers
#    volumes:
#      - ./h2/:/opt/h2-data
#    restart: always

  mariaDB_database:
    container_name: mariaDB
    image: mariadb:latest   # mysql 최신버전을 도커 허브에서 가져옴
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql   # 초기화 SQL 파일 마운트
      - ./mariadb-data:/var/lib/mysql                         # MariaDB 데이터 저장 경로
    restart: always
    healthcheck: # 10초마다 헬스체크
      test: ["CMD-SHELL", "mariadb -u root -proot -e 'SELECT 1'"]
      interval: 10s
      timeout: 10s
      retries: 5

#  member_service:
#    container_name: member_service
#    restart: on-failure
#    build:
#      context: ./MemberService
#      dockerfile: Dockerfile_MemberService
#    ports:
#      - "8081:8081"
#    environment:
#      SPRING_PROFILES_ACTIVE: dev  # application-dev.yml 프로파일 활성화
##      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/dev
##      SPRING_DATASOURCE_USERNAME: root
##      SPRING_DATASOURCE_PASSWORD: root
#    depends_on:
#      - mariaDB_database
#
#  jwt_service:
#    container_name: jwt_service
#    restart: on-failure
#    build:
#      context: ./JwtService
#      dockerfile: Dockerfile_JwtService
#    ports:
#      - "8089:8089"
#    environment:
#      SPRING_PROFILES_ACTIVE: dev  # application-dev.yml 프로파일 활성화
##      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/dev
##      SPRING_DATASOURCE_USERNAME: root
##      SPRING_DATASOURCE_PASSWORD: root
#    depends_on:
#      - mariaDB_database

  feed_service:
    container_name: feed_service
    restart: on-failure
    build:
      context: ./FeedService
      dockerfile: Dockerfile_FeedService
    ports:
      - "9005:9005"
    environment:
      SPRING_PROFILES_ACTIVE: dev  # application-dev.yml 프로파일 활성화
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariaDB:3306/feed_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      mariaDB_database:
        condition: service_healthy

#  api_gateway_service:
#    container_name: api_gateway_service
#    restart: on-failure
#    build:
#      context: ./api-gateway-service
#      dockerfile: Dockerfile_ApiGatewayService
#    ports:
#      - "8000:8000"
#    environment:
#      SPRING_PROFILES_ACTIVE: dev  # application-dev.yml 프로파일 활성화
##      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/dev
##      SPRING_DATASOURCE_USERNAME: root
##      SPRING_DATASOURCE_PASSWORD: root
