CREATE DATABASE IF NOT EXISTS feed_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS MEMBER_DB CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS JWT_DB CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;