spring:
  datasource:
    url: jdbc:mysql://mariaDB:3309/member_db  # MySQL 컨테이너와 연결
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      connection-test-query: SELECT 1

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect
        #배치 인서트
        jdbc:
          batch_size: 10

  data:
    redis:
      host: redis_cli
      port: 6379

management:
    endpoints:
      web:
        exposure:
          include: "*"  # 활성화할 엔드포인트
    health:
      livenessstate:
        enabled: true
      readinessstate:
        enabled: true
