server:
  port: 8081

domain:
  local: "http://localhost"
  dev:
    jwt: "http://jwt-service"

spring:
  datasource:
    hikari:
      maximum-pool-size: 50
  profiles:
    active:  ${SPRING_PROFILES_ACTIVE:local} # 기본값을 application-local.yml 로 설정  -> 환경변수로 변경 가능
  #include: local    # application-local.yml 을 포함시킴
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

#  h2:
#    console:
#      enabled: false
#      settings:
#        web-allow-others: false

  jpa:
    hibernate:
#      ddl-auto: create
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
#        dialect: org.hibernate.dialect.MariaDBDialect

  main:
    allow-bean-definition-overriding: true

# TRACE(상세) > DEBUG(디버깅) > INFO(정보) > WARN(경고) > ERROR(에러) > FATAL(치명적 에러) > OFF(끄기)
#logging:
#  level:
#    root: off
