server:
  port: 0


spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local} # 기본값을 application-local.yml 로 설정  -> 환경변수로 변경 가능
  #include: local    # application-home.yml ? ????

  application:
    name: alarm-service

  datasource:
    url: jdbc:mariadb://localhost:3306/notification_db  # MySQL 컨테이너와 연결
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      connection-test-query: SELECT 1

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        #format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect