server:
  port: 9005


spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local} # 기본값을 application-local.yml 로 설정  -> 환경변수로 변경 가능
  #include: local    # application-home.yml ? ????

  application:
    name: feed-service

upload:
  #path: "/Users/yudong-yeob/desktop/filetest"    # MAC 파일 경로
  path: "C:/Users/User/Desktop/filetest"          # Windows 파일 경로

management:
  endpoints:
    web:
      exposure:
        include: health,info  # 활성화할 엔드포인트
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true