spring:
  datasource:
    url: jdbc:mariadb://mariaDB:3306/feed_db  # MySQL 컨테이너와 연결
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      connection-test-query: SELECT 1


  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        #format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect
        #배치 인서트
        jdbc:
          batch_size: 10

domain:  "http://member-service"